  name: Testes Regressivos


  on:
    schedule:
      - cron: '*/5 * * * 1-5'

  jobs:
    RunTest:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Instalar Java 8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
            cache: maven

        - name: Instalar Chrome
          run: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome*.deb


        - uses: nanasess/setup-chromedriver@v1
        - run: |
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              udo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

        - name: Run Test headless
          run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting

        - name: Gerar relatório quando falhar o teste
          if: always()
          run: mvn cluecumber-report:reporting

        - name: Arquivar relatório
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: report-execution
            path: "**/formated-report/"

        - name: Enviar notificação Slack Sucesso
          uses: rtCamp/action-slack-notify@v2
          if: ${{ success() }}
          env:
            SLACK-WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: qadevops
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://www.pngmart.com/files/20/Success-PNG_Isolated-HD-Pictures.png
            SLACK_MESSAGE: 'Teste Agendado Executado com Sucesso! :white_check_mark:'
            SLACK_TITLE: 'Teste Agendado Executado com Sucesso! :white_check_mark:'
            SLACK_USERNAME: SUCESSO

        - name: Enviar notificação Slack Falha
          uses: rtCamp/action-slack-notify@v2
          if: ${{ failure() }}
          env:
            SLACK-WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: qadevops
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148766.png
            SLACK_MESSAGE: 'Erro ao Executar testes Agendados! :fire:'
            SLACK_TITLE: 'Erro ao Executar testes Agendados! :fire:'
            SLACK_USERNAME: ERRO


